{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"APP - Practical No. 05 - Pawan.ipynb","provenance":[{"file_id":"1fcPqyogTRVV4ZXCT4vGh0CLcRAysVSwo","timestamp":1649666095802},{"file_id":"1E_x0DHR6Ps-VE47DbCB548Rso-ScGsUD","timestamp":1649618479203},{"file_id":"1Q4Rxc_PLAVBzMpizoqGZFlStm2mSncZt","timestamp":1649487822853},{"file_id":"1hcaGnauHz8j54tM1k24aXnjQrvkbE-Fw","timestamp":1647207859533}],"collapsed_sections":[],"authorship_tag":"ABX9TyPtzs0Xuptpdf/i1Pb4P6xk"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["#**Name :** Pawan Gosavi\n","#**Class :** FYBSc CS\n","#**Roll No. :** 01"],"metadata":{"id":"VvzUXLpALn3l"}},{"cell_type":"markdown","source":["# **APP - Practical No. 05**\n","\n","## **Aim :** Write a Python Program to demonstrate different types of Exception Handing."],"metadata":{"id":"YqOjaY2NjRPB"}},{"cell_type":"markdown","source":["# **Exception Handling in Python**\n","\n","  Error in Python can be of two types i.e. Syntax errors and Exceptions. Errors are the problems in a program due to which the program will stop the execution. On the other hand, exceptions are raised when some internal events occur which changes the normal flow of the program."],"metadata":{"id":"_JXgK-rgxgXf"}},{"cell_type":"markdown","source":["## **Difference between Syntax Error and Exceptions**\n","\n","**Syntax Error:** As the name suggests this error is caused by the wrong syntax in the code. It leads to the termination of the program. *italicized text*\n","\n","Example:"],"metadata":{"id":"fMAkfIJjxwKF"}},{"cell_type":"code","source":["# initialize the amount variable\n","amount = 10000\n","\n","# check that You are eligible to\n","# purchase Dsa Self Paced or not\n","if(amount > 2999)\n","print(\"You are eligible to purchase Dsa Self Paced\")\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":131},"id":"NXFdVjh4yOKj","executionInfo":{"status":"error","timestamp":1649955799250,"user_tz":-330,"elapsed":35,"user":{"displayName":"Pawan Gosavi","userId":"05422985579146096715"}},"outputId":"f72759c2-f8d7-4ce1-8933-4fe114eb6e9c"},"execution_count":1,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"ignored","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-8d94ddc68478>\"\u001b[0;36m, line \u001b[0;32m6\u001b[0m\n\u001b[0;31m    if(amount > 2999)\u001b[0m\n\u001b[0m                     ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"]}]},{"cell_type":"markdown","source":["**Exceptions :** Exceptions are raised when the program is syntactically correct, but the code resulted in an error. This error does not stop the execution of the program, however, it changes the normal flow of the program.\n","\n","Example:"],"metadata":{"id":"4Emkd7XFya5u"}},{"cell_type":"code","source":["# initialize the amount variable\n","marks = 10000\n","\n","# perform division with 0\n","a = marks / 0\n","print(a)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":218},"id":"5ioS-eGPyaNb","executionInfo":{"status":"error","timestamp":1649955802347,"user_tz":-330,"elapsed":28,"user":{"displayName":"Pawan Gosavi","userId":"05422985579146096715"}},"outputId":"25844af6-da35-439e-8d78-beb77e899a59"},"execution_count":2,"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-5f312778a383>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;31m# perform division with 0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m \u001b[0ma\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmarks\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      6\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}]},{"cell_type":"markdown","source":["In the above example raised the ZeroDivisionError as we are trying to divide a number by 0."],"metadata":{"id":"LZSoaMM8ysT-"}},{"cell_type":"markdown","source":["## **Try and Except Statement – Catching Exceptions**\n","\n","  Try and except statements are used to catch and handle exceptions in Python. Statements that can raise exceptions are kept inside the try clause and the statements that handle the exception are written inside except clause.\n","\n","  Example: Let us try to access the array element whose index is out of bound and handle the corresponding exception."],"metadata":{"id":"AGxU5SJuyvds"}},{"cell_type":"code","source":["# Python program to handle simple runtime error\n","#Python 3\n","\n","a = [1, 2, 3]\n","try:\n","\tprint (\"\\nSecond element = %d\" %(a[1]))\n","\n","\t# Throws error since there are only 3 elements in array\n","\tprint (\"\\nFourth element = %d\" %(a[3]))\n","\n","except:\n","\tprint (\"\\nAn error occurred\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"oiDpnHGcy4yQ","executionInfo":{"status":"ok","timestamp":1649955805150,"user_tz":-330,"elapsed":15,"user":{"displayName":"Pawan Gosavi","userId":"05422985579146096715"}},"outputId":"df3e9f1c-76b0-4635-cb42-5993a165e8e2"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","Second element = 2\n","\n","An error occurred\n"]}]},{"cell_type":"markdown","source":["  In the above example, the statements that can cause the error are placed inside the try statement (second print statement in our case). The second print statement tries to access the fourth element of the list which is not there and this throws an exception. This exception is then caught by the except statement."],"metadata":{"id":"y8p48UnMy-kP"}},{"cell_type":"markdown","source":["## **Catching Specific Exception**\n","\n","  A try statement can have more than one except clause, to specify handlers for different exceptions. Please note that at most one handler will be executed. For example, we can add IndexError in the above code. The general syntax for adding specific exceptions are – \n","\n","```\n","try:\n","    # statement(s)\n","except IndexError:\n","    # statement(s)\n","except ValueError:\n","    # statement(s)\n","```\n","\n","\n","Example : Catching specific exception in Python"],"metadata":{"id":"_Yub9gLfzUwu"}},{"cell_type":"code","source":["# Program to handle multiple errors with one\n","# except statement\n","# Python 3\n","\n","def fun(a):\n","\tif a < 4:\n","\n","\t\t# throws ZeroDivisionError for a = 3\n","\t\tb = a/(a-3)\n","\n","\t# throws NameError if a >= 4\n","\tprint(\"\\nValue of b = \", b)\n","\t\n","try:\n","\tfun(3)\n","\tfun(5)\n","\n","# note that braces () are necessary here for\n","# multiple exceptions\n","except ZeroDivisionError:\n","\tprint(\"\\nZeroDivisionError Occurred and Handled\")\n","except NameError:\n","\tprint(\"\\nNameError Occurred and Handled\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"w-rVAd0dzvx6","executionInfo":{"status":"ok","timestamp":1649955811216,"user_tz":-330,"elapsed":628,"user":{"displayName":"Pawan Gosavi","userId":"05422985579146096715"}},"outputId":"a7ae258f-0c29-4b10-a5c0-7b9d43eeb48d"},"execution_count":4,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","ZeroDivisionError Occurred and Handled\n"]}]},{"cell_type":"markdown","source":["## **Try with Else Clause**\n","\n","  In python, you can also use the else clause on the try-except block which must be present after all the except clauses. The code enters the else block only if the try clause does not raise an exception.\n","\n","Example : Try with else clause"],"metadata":{"id":"cqSuBCUcz-AC"}},{"cell_type":"code","source":["# Program to depict else clause with try-except\n","# Python 3\n","# Function which returns a/b\n","def AbyB(a , b):\n","\ttry:\n","\t\tc = ((a+b) / (a-b))\n","\texcept ZeroDivisionError:\n","\t\tprint (\"\\na/b result in 0\")\n","\telse:\n","\t\tprint (c)\n","\n","# Driver program to test above function\n","AbyB(2.0, 3.0)\n","AbyB(3.0, 3.0)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"XKmlMhj10Idp","executionInfo":{"status":"ok","timestamp":1649955814499,"user_tz":-330,"elapsed":20,"user":{"displayName":"Pawan Gosavi","userId":"05422985579146096715"}},"outputId":"55d84410-a3a9-4f47-dc49-2b11e567ccb3"},"execution_count":5,"outputs":[{"output_type":"stream","name":"stdout","text":["-5.0\n","\n","a/b result in 0\n"]}]},{"cell_type":"markdown","source":["## **Finally Keyword in Python**\n","\n","  Python provides a keyword finally, which is always executed after the try and except blocks. The final block always executes after normal termination of try block or after try block terminates due to some exception.\n","\n","Syntax:\n","\n","```\n","try:\n","    # Some Code.... \n","\n","except:\n","    # optional block\n","    # Handling of exception (if required)\n","\n","else:\n","    # execute if no exception\n","\n","finally:\n","    # Some code .....(always executed)\n","```\n","\n","Example:"],"metadata":{"id":"YV-F3ODi0fY3"}},{"cell_type":"code","source":["# Python program to demonstrate finally\n","\n","# No exception Exception raised in try block\n","try:\n","\tk = 5//0 # raises divide by zero exception.\n","\tprint(k)\n","\n","# handles zerodivision exception\n","except ZeroDivisionError:\n","\tprint(\"\\nCan't divide by zero\")\n","\n","finally:\n","\t# this block is always executed\n","\t# regardless of exception generation.\n","\tprint('\\nThis is always executed')\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"-itfZHOk0zmC","executionInfo":{"status":"ok","timestamp":1649955820357,"user_tz":-330,"elapsed":553,"user":{"displayName":"Pawan Gosavi","userId":"05422985579146096715"}},"outputId":"420d573a-4862-4548-d6c4-8d3a098c36e0"},"execution_count":6,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","Can't divide by zero\n","\n","This is always executed\n"]}]},{"cell_type":"markdown","source":["## **Raising Exception**\n","\n","  The raise statement allows the programmer to force a specific exception to occur. The sole argument in raise indicates the exception to be raised. This must be either an exception instance or an exception class (a class that derives from Exception)."],"metadata":{"id":"uEUEIBZI0-_M"}},{"cell_type":"code","source":["# Program to depict Raising Exception\n","\n","try:\n","\traise NameError(\"Hi there\") # Raise Error\n","except NameError:\n","\tprint (\"\\nAn exception\")\n","\traise # To determine whether the exception was raised or not"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":270},"id":"Sf590vKt1Ei7","executionInfo":{"status":"error","timestamp":1649955823434,"user_tz":-330,"elapsed":560,"user":{"displayName":"Pawan Gosavi","userId":"05422985579146096715"}},"outputId":"b1052b96-91b1-4fc4-ffa0-3ba3e9aed732"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","An exception\n"]},{"output_type":"error","ename":"NameError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-7-ba88b72298fc>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mNameError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Hi there\"\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;31m# Raise Error\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m \u001b[0;32mexcept\u001b[0m \u001b[0mNameError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m         \u001b[0mprint\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0;34m\"\\nAn exception\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mNameError\u001b[0m: Hi there"]}]},{"cell_type":"markdown","source":["  The output of the above code will simply line printed as “An exception” but a Runtime error will also occur in the last due to the raise statement in the last line. So, the output on your command line will look like above."],"metadata":{"id":"-Wsh4bAs1Kib"}},{"cell_type":"markdown","source":["#**Student's Task**"],"metadata":{"id":"wtpYwiiF3vh_"}},{"cell_type":"markdown","source":["## **Try, Except, else and Finally in Python**"],"metadata":{"id":"xjr03kNW60-o"}},{"cell_type":"code","source":["# Python code to illustrate Try, Except, else and Finally Block.\n","\n","# working of try()\n","def divide(x, y):\n","\ttry:\n","\t\t# Floor Division : Gives only Fractional\n","\t\t# Part as Answer\n","\t\tresult = x // y\n","\texcept ZeroDivisionError:\n","\t\tprint(\"\\nSorry ! You are dividing by zero \")\n","\telse:\n","\t\tprint(\"\\nYeah ! Your answer is :\", result)\n","\tfinally:\n","\t\t# this block is always executed\n","\t\t# regardless of exception generation.\n","\t\tprint('\\nThis is always executed')\n","\n","# Look at parameters and note the working of Program\n","divide(3, 2)\n","divide(3, 0)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"RVZf_dKf60-1","executionInfo":{"status":"ok","timestamp":1649955828423,"user_tz":-330,"elapsed":510,"user":{"displayName":"Pawan Gosavi","userId":"05422985579146096715"}},"outputId":"63b4d744-ee0b-4287-ca99-f744e7411ceb"},"execution_count":8,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","Yeah ! Your answer is : 1\n","\n","This is always executed\n","\n","Sorry ! You are dividing by zero \n","\n","This is always executed\n"]}]}]}